_wandb:
    value:
        cli_version: 0.25.1
        e:
            zjbciy6akm24aq1mcwkvccs2aid9a6e0:
                codePath: testConnection.py
                codePathLocal: testConnection.py
                email: efyjn8@nottingham.edu.my
                executable: D:\Jeremy\UoN\Year 4\Final Year Project Coding\FYP_BaselineNN\.venv\Scripts\python.exe
                git:
                    commit: c788f492a6e4cc6e5db309372fba5fdccf2c2a01
                    remote: https://github.com/JeremyNg77/FYP_BaselineNN.git
                host: LAPTOP-3MEUV5NR
                os: Windows-10-10.0.22631-SP0
                program: d:\Jeremy\UoN\Year 4\Final Year Project Coding\FYP_BaselineNN\testConnection.py
                python: CPython 3.10.4
                root: D:\Jeremy\UoN\Year 4\Final Year Project Coding\FYP_BaselineNN
                startedAt: "2026-03-12T09:11:12.186841Z"
                writerId: zjbciy6akm24aq1mcwkvccs2aid9a6e0
        m: []
        python_version: 3.10.4
        t:
            "3":
                - 2
                - 13
            "4": 3.10.4
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
